add wallet balance endpoint
xmtp/xps-gateway pull request #56
Opened 2024-02-05 16:27 UTC by tsachiherman

## TODO:

description for https://github.com/xmtp/xps-gateway/issues/23 goes here.

2024-02-06 15:48 UTC, insipx commented
I think the more idiomatic way would be doing something like this:

```rust
pub struct WalletBalance {
    /// The balance for the wallet; just the number itself.
    #[serde(rename = "balance")]
    pub balance: U256,
    /// The unit used for the balance; formatted as "ETH"
    #[serde(rename = "unit")]
    pub unit: String,
}
```

with a custom display implementation:
```rust
impl Display for WalletBalance {
// ...
}
```

I would also be in favor of turning `unit` into an enum,

```rust
pub struct Unit {
    Eth,
    Other(String),
}
```

Since we are mostly going to be using Eth, and down the line we can add other chains we use

2024-02-08 21:09 UTC, insipx requested changes

2024-02-08 21:10 UTC, insipx commented
just a small nit, if we unwrap in a method used by the RPC our server will go down

Otherwise looking good! Ready to approve after that is turned into an error

2024-02-09 00:29 UTC, jac18281828 reviewed
This looks like a good start.  Make sure to address those codecov warnings about lack of tests.

2024-02-12 14:39 UTC, merged