Remove references to `gateway`
xmtp/xps-gateway pull request #57
Opened 2024-02-08 21:52 UTC by insipx

2024-02-08 21:53 UTC, insipx commented on .github/workflows/ghcr-image.yml
>  name: Docker Image Build Push
this re-formatting keeps happening to me, I think it's because we're using different YAML formatters in our editors, so whenever I open a file it auto-reformats

I don't mind the previous format, but lets consolidate on one and create a config file for it somewehre

2024-02-09 00:33 UTC, jac18281828 requested changes
I like this.  I'd just ask that you revert whitespace only changes unless that includes a code change.

2024-02-09 00:33 UTC, jac18281828 commented on .github/workflows/ghcr-image.yml
>  name: Docker Image Build Push
What formatter are you using?   Would it be possible to revert the changes if you have not actually changed anything?

2024-02-09 00:33 UTC, insipx commented on .github/workflows/ghcr-image.yml
>  name: Docker Image Build Push
Yeah I can revert those changes

2024-02-09 00:34 UTC, insipx commented on .github/workflows/ghcr-image.yml
>  name: Docker Image Build Push
I'm using [yamlfmt](https://github.com/google/yamlfmt) with default settings

2024-02-09 01:14 UTC, insipx commented
> What formatter are you using?
I'm using [yamlfmt](https://github.com/google/yamlfmt) with default settings, can probably configure to whatever you got, if you have a config file somewhere or the formatter you're using

2024-02-09 01:32 UTC, jac18281828 commented
> > What formatter are you using?
> 
> I'm using [yamlfmt](https://github.com/google/yamlfmt) with default settings

I added a note to try to set that up.  I'll see how to get synced up.

2024-02-09 20:34 UTC, jac18281828 approved these changes
Thanks!  All looks great!  Appreciate the cleanup.

2024-02-09 20:56 UTC, 37ng approved these changes

2024-02-09 21:05 UTC, 37ng commented
Are we planning to change the repo name from `xps-gateway` to `xps`?

2024-02-09 22:22 UTC, insipx commented
> Are we planning to change the repo name from `xps-gateway` to `xps`?

makes sense to me

2024-02-12 18:53 UTC, merged